#!/bin/bash

set -e
set -o nounset
set -o pipefail

echo "Getting the presigned url"

export RESP=$(curl -XPOST -H "Authorization: Basic ${KOBITON_AUTH}" -H "Content-type: application/json" -d "{
            \"filename\" : \"upload.$1\"}" https://api.kobiton.com/v1/apps/uploadUrl)

echo $$RESP
# shellcheck disable=SC2091
$(echo $RESP | jq -r 'keys[] as $k | "export \($k)=\(.[$k])"')

echo $url
echo $appPath

echo "Uploading to s3 bucket"

curl -T $2 \
  -H "Content-Type: application/octet-stream" \
  -H "x-amz-tagging: unsaved=true" \
  -X PUT $url

echo "Creating an upload on kobiton"

curl -X POST https://api.kobiton.com/v1/apps \
  -H "Authorization: Basic ${KOBITON_AUTH}" \
  -H 'Content-Type: application/json' \
  -d "{\"filename\" :  \"upload.$1 \", \"appPath\" :\"$appPath\"}"

echo "Getting the new upload id"

export ID=$(curl https://api.kobiton.com/v1/apps \
  -H "Authorization: Basic ${KOBITON_AUTH}" \
  -H 'Content-Type: application/json' |
  jq -r .apps[1].id)''
echo $ID
